//Arquivo para teste da rota para login


#Teste para o login valido (deve fazer o login e retornar o id)
###
POST http://localhost:3001/users
Content-Type: application/json

{
  "username": "teste",
  "password": "1qwe2asd"
}


#Teste para o login invalido (deve dar erro de credencias invalidas)
###
POST http://localhost:3000/localities/login
Content-Type: application/json

{
  "username": "FORTALEZA",
  "password": "1qwe2as"
}
