//Rotas de teste para a criação da localidade


//Rota para testar a criação da localidade
###
POST http://localhost:3000/localities
Content-Type: application/json

{
  "locality": "SALINAS",
  "password": "1qwe2asd"
}

//Rota para testar o erro quando senha não cumprir os requisitos
###
POST http://localhost:3000/localities
Content-Type: application/json

{
  "locality": "BELÉM",
  "password": "123"
}

//Rota para testar quando a localidade não cumprir os requisitos
###
POST http://localhost:3000/localities
Content-Type: application/json

{
  "locality": "B",
  "password": "1qwe2asd"
}