//Arquivo para teste da rota para criação da localidade


# Teste para a criação válida (Deve retornar o id da localidade)
###
POST http://localhost:3000/localities/create
Content-Type: application/json

{
  "username": "BELÉM",
  "password": "1qwe2asd"
}


# Teste para quando se passar uma senha inválida (Deve retornar erro de validação referente a senha)
###
POST http://localhost:3000/localities/create
Content-Type: application/json

{
  "username": "CURUÇA",
  "password": "123"
}


# Teste para quando se passar uma localidede invalida (Deve retornar erro de validação refenrete a localide)
###
POST http://localhost:3000/localities/create
Content-Type: application/json

{
  "username": "B",
  "password": "1qwe2asd"
}

#Teste para quando não se passar algum dos dados (Deve retornar erro de validação referente ao campo que não foi passado)
###
POST http://localhost:3000/localities/create
Content-Type: application/json

{
  "username": "",
  "password": "1qwe2asd"
}
